In [11]:
#Import Pandas library

In [5]:
import pandas as pd

In [ ]:
#Read both the csv files

In [6]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')

In [7]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [8]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
#Merge both the files

In [9]:
ratings = pd.merge(movies,ratings)

In [10]:
ratings.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [12]:
#Drop columns which are not useful to us

In [13]:
ratings.drop(['genres','timestamp'], axis = 1)

        movieId                                      title  userId  rating
0             1                           Toy Story (1995)       1     4.0
1             1                           Toy Story (1995)       5     4.0
2             1                           Toy Story (1995)       7     4.5
3             1                           Toy Story (1995)      15     2.5
4             1                           Toy Story (1995)      17     4.5
...         ...                                        ...     ...     ...
100831   193581  Black Butler: Book of the Atlantic (2017)     184     4.0
100832   193583               No Game No Life: Zero (2017)     184     3.5
100833   193585                               Flint (2017)     184     3.5
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184     3.5
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331     4.0

[100836 rows x 4 columns]

In [15]:
user_ratings = ratings.pivot_table(index=['userId'],columns=['title'],values='rating')

In [16]:
user_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#Removing movies which less than 10 users have rated and replace Nan with 0

In [18]:
user_ratings = user_ratings.dropna(thresh = 10,axis =1)

In [19]:
user_ratings = user_ratings.fillna(0)

In [20]:
user_ratings.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
#Building similarity matrix

In [22]:
similarity = user_ratings.corr(method = 'pearson')

In [23]:
similarity.head(20)

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,0.063117,-0.023768,0.143482,0.011998,0.087931,0.224052,0.034223,0.009277,0.008331,...,0.017477,0.032470,0.134701,0.153158,0.101301,0.049897,0.003233,0.187953,0.062174,0.353194
(500) Days of Summer (2009),0.063117,1.000000,0.142471,0.273989,0.193960,0.148903,0.142141,0.159756,0.135486,0.200135,...,0.374515,0.178655,0.068407,0.414585,0.355723,0.252226,0.216007,0.053614,0.241092,0.125905
10 Cloverfield Lane (2016),-0.023768,0.142471,1.000000,-0.005799,0.112396,0.006139,-0.016835,0.031704,-0.024275,0.272943,...,0.242663,0.099059,-0.023477,0.272347,0.241751,0.195054,0.319371,0.177846,0.096638,0.002733
10 Things I Hate About You (1999),0.143482,0.273989,-0.005799,1.000000,0.244670,0.223481,0.211473,0.011784,0.091964,0.043383,...,0.243118,0.104858,0.132460,0.091853,0.158637,0.281934,0.050031,0.121029,0.130813,0.110612
"10,000 BC (2008)",0.011998,0.193960,0.112396,0.244670,1.000000,0.234459,0.119132,0.059187,-0.025882,0.089328,...,0.260261,0.087592,0.094913,0.184521,0.242299,0.240231,0.094773,0.088045,0.203002,0.083518
101 Dalmatians (1996),0.087931,0.148903,0.006139,0.223481,0.234459,1.000000,0.285112,0.119843,0.072399,0.029967,...,0.114968,0.077232,0.096294,0.067134,0.113224,0.184324,0.054024,0.047804,0.156932,0.078734
101 Dalmatians (One Hundred and One Dalmatians) (1961),0.224052,0.142141,-0.016835,0.211473,0.119132,0.285112,1.000000,0.134037,0.017264,-0.046277,...,0.120302,0.125816,0.049818,0.083650,0.171654,0.274260,0.077594,0.085606,0.248820,0.171118
12 Angry Men (1957),0.034223,0.159756,0.031704,0.011784,0.059187,0.119843,0.134037,1.000000,0.132979,0.058862,...,0.104518,0.028415,0.079905,0.241435,0.144652,0.122107,0.056742,-0.001708,0.074306,0.102744
12 Years a Slave (2013),0.009277,0.135486,-0.024275,0.091964,-0.025882,0.072399,0.017264,0.132979,1.000000,0.249931,...,0.024045,0.038127,0.013786,0.190366,0.104150,0.017351,0.063325,0.002528,0.037469,0.004213
127 Hours (2010),0.008331,0.200135,0.272943,0.043383,0.089328,0.029967,-0.046277,0.058862,0.249931,1.000000,...,0.223135,0.154299,0.012907,0.364841,0.198926,0.091416,0.225747,0.128638,0.153335,0.002912
13 Going on 30 (2004),0.049700,0.297152,-0.027835,0.321071,0.167098,0.188467,0.218406,-0.027672,0.092133,0.043314,...,0.103892,0.171578,0.024181,0.134812,0.108230,0.225685,0.069602,0.010007,0.139022,0.021094
"13th Warrior, The (1999)",0.176071,0.072835,-0.029983,0.215828,0.163148,0.004213,0.135894,0.084760,0.040699,0.005800,...,0.104176,0.020703,0.120064,0.166900,0.074339,0.110602,0.043481,0.193831,0.120495,0.164405
1408 (2007),0.131993,0.226574,0.181245,0.069470,0.133706,0.159777,0.227193,0.189497,0.227912,0.226178,...,0.255607,0.080251,0.085942,0.489065,0.340620,0.250310,0.155936,0.185768,0.336272,0.130120
15 Minutes (2001),0.104500,0.087240,0.017315,0.223197,0.190482,0.023682,0.150835,0.001958,0.036131,0.027306,...,0.203207,0.146579,0.202411,0.148711,0.205183,0.161740,0.052809,0.149044,0.328057,0.122113
17 Again (2009),0.047271,0.342948,-0.019197,0.231261,0.174499,0.064464,0.121410,0.049762,0.177934,0.054016,...,0.263390,0.122126,0.060692,0.194117,0.274326,0.127872,0.098426,0.044268,0.117481,0.031311
1984 (Nineteen Eighty-Four) (1984),0.184452,0.038255,0.049227,0.131719,0.076915,0.060264,0.016212,0.083904,-0.024158,0.042696,...,0.086713,0.097415,0.248409,0.044366,0.033937,0.119897,0.055617,0.348052,0.228618,0.056773
2 Days in the Valley (1996),0.092824,0.040104,-0.020711,0.084953,0.074188,-0.011668,0.012298,0.005600,0.045062,0.044682,...,0.034641,0.051850,0.132592,0.082067,0.039383,0.079517,0.019376,0.208630,0.114278,0.157638
"2 Fast 2 Furious (Fast and the Furious 2, The) (2003)",0.084066,0.241906,0.097364,0.241569,0.383957,0.226195,0.278202,0.038303,0.042812,0.206104,...,0.325163,0.234824,0.028620,0.245552,0.258282,0.392528,0.228663,0.066253,0.536836,0.067338
"20,000 Leagues Under the Sea (1954)",0.166599,0.001739,0.012478,-0.025007,0.062390,0.048827,0.077642,0.095175,-0.026507,-0.027924,...,0.060311,0.028748,0.150319,0.044810,0.005268,0.048607,-0.018962,0.015235,0.071050,0.097238
2001: A Space Odyssey (1968),0.205977,0.113616,0.099310,0.085974,0.043458,0.110844,0.102230,0.195909,0.123191,0.140796,...,0.150649,0.097214,0.257591,0.350332,0.196175,0.148409,0.099252,0.306034,0.164096,0.182865

In [ ]:
#Function to get similar movies

In [24]:
def get_similar_movies(movie_name,user_rating):
    similar_score = similarity[movie_name] * (user_rating -2.5)
    similar_score = similar_score.sort_values(ascending = False)
    
    return similar_score

In [26]:
romantic_movies_user = [("(500) Days of Summer (2009)",5),("Alice in Wonderland (2010)",3),("Aliens (1986)",1),("2001: A Space Odyssey (1968)",2)]

similar_movies = pd.DataFrame()

for movie,rating in romantic_movies_user:
    similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index = True)

similar_movies.head(10)

,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
0,0.157792,2.500000,0.356179,0.684973,0.484900,0.372257,0.355353,0.399389,0.338715,0.500338,...,0.936288,0.446637,0.171018,1.036463,0.889309,0.630565,0.540017,0.134034,0.602730,0.314763
1,-0.016276,0.203998,0.126834,0.113241,0.092218,0.085790,0.072825,0.097794,0.083822,0.084897,...,0.159907,0.085502,0.011564,0.176888,0.168302,0.121710,0.072590,0.025695,0.081764,0.027540
2,-0.304722,-0.062634,-0.214700,-0.118754,-0.037059,-0.063992,-0.170195,-0.280090,-0.016283,-0.102493,...,-0.147339,-0.162387,-0.368712,-0.281119,-0.263686,-0.228562,-0.144292,-0.410899,-0.242935,-0.238410
3,-0.102988,-0.056808,-0.049655,-0.042987,-0.021729,-0.055422,-0.051115,-0.097954,-0.061595,-0.070398,...,-0.075325,-0.048607,-0.128795,-0.175166,-0.098088,-0.074205,-0.049626,-0.153017,-0.082048,-0.091432

In [27]:
similar_movies.sum().sort_values(ascending=False).head(20)

(500) Days of Summer (2009)                      2.584556
Alice in Wonderland (2010)                       1.395229
Silver Linings Playbook (2012)                   1.254800
Yes Man (2008)                                   1.116264
Adventureland (2009)                             1.112235
Marley & Me (2008)                               1.108381
About Time (2013)                                1.102192
Crazy, Stupid, Love. (2011)                      1.088757
50/50 (2011)                                     1.086517
Help, The (2011)                                 1.075963
Up in the Air (2009)                             1.053037
Holiday, The (2006)                              1.034470
Friends with Benefits (2011)                     1.030875
Notebook, The (2004)                             1.025880
Easy A (2010)                                    1.015771
Secret Life of Walter Mitty, The (2013)          0.997979
Perks of Being a Wallflower, The (2012)          0.967425
Toy Story 3 (2010)                               0.963276
Ugly Truth, The (2009)                           0.959079
Harry Potter and the Half-Blood Prince (2009)    0.954180
dtype: float64

In [ ]:
#Recommendation for comedy movies

In [29]:
comedy_movies_user = [("Toy Story (1995)",5),("Father of the Bride Part II (1995)",4),("Aliens (1986)",1),("2001: A Space Odyssey (1968)",2)]

similar_movies = pd.DataFrame()

for movie,rating in comedy_movies_user:
    similar_movies = similar_movies.append(get_similar_movies(movie,rating),ignore_index = True)

similar_movies.head(10)

similar_movies.sum().sort_values(ascending=False).head(20)

Toy Story (1995)                              2.412416
Father of the Bride Part II (1995)            1.984087
Hunchback of Notre Dame, The (1996)           1.072099
Twister (1996)                                1.051169
Mr. Holland's Opus (1995)                     1.028879
Nutty Professor, The (1996)                   1.026478
Sudden Death (1995)                           0.981866
101 Dalmatians (1996)                         0.977150
Willy Wonka & the Chocolate Factory (1971)    0.962517
James and the Giant Peach (1996)              0.960027
Tin Cup (1996)                                0.954466
Sabrina (1995)                                0.936511
Juror, The (1996)                             0.927350
Beauty and the Beast (1991)                   0.904223
Sgt. Bilko (1996)                             0.903839
Mrs. Doubtfire (1993)                         0.901995
Lion King, The (1994)                         0.894744
Happy Gilmore (1996)                          0.891053
Grumpier Old Men (1995)                       0.884157
Babe (1995)                                   0.883815
dtype: float64